version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: it_rock_challenge_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-it_rock_challenge_pg}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-it_rock_challenge_pg}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: it_rock_challenge_redis
    command: >
      sh -c "redis-server
      --appendonly yes
      ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
